# -*- encoding : utf-8 -*-
# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

ENV["RAILS_ENV"] ||= 'cucumber'

require File.expand_path(File.dirname(__FILE__) + '/../../config/environment')

require 'pry' # TODO: remove, only for development porpouse

require 'cucumber/formatter/unicode' # Remove this line if you don't want Cucumber Unicode support
require 'cucumber/rails/rspec'
require 'cucumber/rails/world'
require 'cucumber/web/tableish'
require 'cucumber/rspec/doubles'

require 'capybara/rails'
require 'capybara/cucumber'
require 'capybara/session'
require 'capybara/poltergeist'

require 'email_spec/cucumber'


# Capybara.default_wait_time = 2
Capybara.default_selector  = :css


##
# Poltergeist - A PhantomJS driver for Capybara
# Take a look at https://github.com/teampoltergeist/poltergeist#customization for more customizations
Capybara.javascript_driver = :poltergeist
Capybara.register_driver :poltergeist do |app|
  Capybara::Poltergeist::Driver.new(app, {
    # js_errors: false,
    timeout: 600  # TODO: remove, only for debugging porpouse
  })
end

# Using poltergeist_debug you can insert page.driver.debug into your tests to pause the test
# and launch a browser which gives you the WebKit inspector to view your test run with.
# Capybara.javascript_driver = :poltergeist_debug
# Capybara.register_driver :poltergeist_debug do |app|
#   Capybara::Poltergeist::Driver.new(app, {
#     inspector: true,
#     timeout:   600,
#     js_errors: true
#   })
# end

##
# DatabaseCleaner
# How to clean your database when transactions are turned off. See
# http://github.com/bmabey/database_cleaner for more info.
if defined?(ActiveRecord::Base)
  require 'database_cleaner'
  DatabaseCleaner.strategy = :truncation
end

require 'rack/test'
require 'rack/test/cookie_jar'

Before do
  # Tests are written to target non-community version, except where noted (I am using the community version)
  Teambox.config.community = false
  Teambox.config.allow_signups = true
end
